language: java
jdk:
  - openjdk7
  - oraclejdk8


sudo: false
env:
  global:
    CRATE_TESTS_SQL_REQUEST_TIMEOUT="10"
    JAVA7_HOME="/usr/lib/jvm/java-7-oracle"
    _JAVA_OPTIONS="-Xmx1g -XX:MaxPermSize=256m"

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false

before_install:
  - ulimit -u 65535

script: ./gradlew -PtestForks=2 test itest -s

after_success:
  - ./gradlew jacocoReport coveralls
