language: java
jdk:
  - openjdk7
env:
  global:
    _JAVA_OPTIONS="-Xmx512m -XX:MaxPermSize=128m -XX:MaxDirectMemorySize=512m"
notifications:
  email: false

before_install:
  - ulimit -u 65535

script: ./gradlew --parallel -PtestForks=2 test itest -s

after_success:
  - ./gradlew jacocoReport coveralls
